# true = enable autopickup
# false = disable autopickup

enable-autopickup: true

# Features:

# Fortune support
# No break worldguard
# Less resource usage

messages:
  no_permission: "&4&lERROR: &cYou dont have permissions."

  quit: "&8[&c-&8] &r{player_name}"
  join: "&8[&a+&8] &r{player_name}"
  
  fly_enable: "&9&l FLY MODE &7| &a&lENABLE"
  fly_disable: "&9&l FLY MODE &7| &c&lDISABLE"
  
  teleported_to_spawn: "&aYou were teleported to spawn successfully"
  
  welcome: |-
   &f
   &9&l WELCOME &7| &b&lMESSAGE
   &f &f
   &7 This is a example
   &7 You can edit this in &bconfig.yml
   &f &f
  
  spawn: |-
   &f
   &9&l SPAWN &7| &e&lINCOMING
   &f &f
   &7 Go to spawn...
   &f &f
   
  help: |-
   &f
   &9&l HELP &7| &b&lCOMMAND
   &f &f
   &7 &7Hi, this is a example
   &7 &7You can edit this in &bconfig.yml
   &f &f
   &7 &7Plugin by &9iChocoMC_ &7| &91.0